# Create `*.secrets.yml` (app.secrets.yml, db.secrets.yml, etc) files in this folder 
# to store passwords, api keys and other secure credentials

# This file can then be deleted

# app.secrets.yml
EXAMPLE_SECRET: XXXX
EXAMPLE_API_KEY: XXXX

# db.secrets.yml
PASSWORD: XXXX
