# REPLACE WITH secrets.yml in config directory

# This example file can be deleted or used to store example contents of secrets config
SECRET_PASSWORD: XXXX-XXXX
DB_PASSWORD: a4d^5Y9AahGj # Sample password for docker db service
